/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32F401Re.h";
#include "stm32F401Re_gpio_driver.h"
#include "stm32F401Re_spi_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Command codes
#define COMMAND_LED_CTRL      0x50
#define COMMAND_SENSOR_READ   0x51
#define COMMAND_LED_READ      0x52
#define COMMAND_PRINT         0x53
#define COMMAND_ID_READ       0x54
#define ACK					  0xF5
#define NACK				  0xA5

// LED states
#define LED_ON                1
#define LED_OFF               0

// Arduino analog pins
#define ANALOG_PIN0           0
#define ANALOG_PIN1           1
#define ANALOG_PIN2           2
#define ANALOG_PIN3           3
#define ANALOG_PIN4           4

// Arduino LED pin
#define LED_PIN               9




/*

PA5 SPI1SCLK

PA6 SPI1MISO

PA7 SPI1MOSI

PA4 SPI1NSS


*/

static void delay() {

	for (uint32_t i = 0; i < 500000 / 2; i++);

}


static void Button_Init(void) {

	GPIO_Pin_Handle_t Button;

	Button.pGPIOx = GPIOC;

	Button.GPIO_pin_config.GPIO_PinMode = GPIO_MODE_IN;

	Button.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_13;

	Button.GPIO_pin_config.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

	Button.GPIO_pin_config.GPIO_PinoutputType = GPIO_OP_TYPE_PP;

	Button.GPIO_pin_config.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&Button);

}

static void SPI1_GPIOInit() {

	GPIO_Pin_Handle_t SpiPins;

	SpiPins.pGPIOx = GPIOA;

	SpiPins.GPIO_pin_config.GPIO_AltFuncMode = 5;

	SpiPins.GPIO_pin_config.GPIO_PinMode = GPIO_MODE_ALTFN;

	SpiPins.GPIO_pin_config.GPIO_PinoutputType = GPIO_OP_TYPE_PP;

	SpiPins.GPIO_pin_config.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	SpiPins.GPIO_pin_config.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

	GPIO_PeriClockControl(GPIOA, ENABLE);

	//SCLK

	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_5;
	GPIO_Init(&SpiPins);

	//MISO
	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_6;
	GPIO_Init(&SpiPins);

	//MOSI
	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_7;
	GPIO_Init(&SpiPins);


	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_4;
	GPIO_Init(&SpiPins);


	//NSS must be pulled to VDD even when it's not used,  nss should be connected to ground in hardware control mode or SSI should be set to 1 in software control mode
	//As if SSI is set 0 or NSS is pulled to low for master, it should be in multimaster mode in which another master is taking control
	//IF IN SOFTWARE SLAVE MANAGEMENT MODE, IF SSI IS NOT SET TO 1, MODF FLAG WILL BE SET
}

static void SPI1_Init() {

	SPI_Handle_t spi1;

	spi1.pSPIx = SPI1;

	spi1.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;


	spi1.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;


	spi1.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;


	spi1.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;


	spi1.SPIConfig.SPI_DFF = SPI_DFF_8BITS;


	spi1.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;


	spi1.SPIConfig.SPI_SSM = SPI_SSM_DI;


	SPI_Init(&spi1);

}

uint8_t Verify(uint8_t code) {

	if (code == ACK) {
	
		return 1;
	
	}
	else if (code == NACK) {
	
		return 0;
	
	}

}

int main(void)
{


	SPI1_GPIOInit();

	SPI1_Init();

	Button_Init();

	//SPI_SSIConfig(SPI1, ENABLE);
	SPI_SSOEConfig(SPI1, ENABLE);


	while (1) {

		uint8_t dummy_send = 0xff;

		uint8_t dummy_read = 0xf1;

		uint8_t command_code;

		uint8_t confirmation_code;

		uint8_t arg[2];

		uint8_t analog_read;

		while (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));

		delay();

		SPI_PeripheralControl(SPI1, ENABLE);

		command_code = COMMAND_LED_CTRL;

		SPI_SendData(SPI1,&command_code, 1);

		SPI_ReceiveData(SPI1, &dummy_read, 1);

		SPI_SendData(SPI1, &dummy_send, 1);

		SPI_ReceiveData(SPI1, &confirmation_code, 1);

		if (Verify(confirmation_code)) {

			arg[0] = LED_PIN;

			arg[1] = LED_ON;

			SPI_SendData(SPI1, arg, 2);

		}

		while (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13));

		command_code = COMMAND_SENSOR_READ;

		SPI_SendData(SPI1, &command_code, 1);

		SPI_ReceiveData(SPI1, &dummy_read, 1);

		SPI_SendData(SPI1, &dummy_send, 1);

		SPI_ReceiveData(SPI1, &confirmation_code, 1);

		if (Verify(confirmation_code)) {

			arg[0] = ANALOG_PIN0;

			SPI_SendData(SPI1, arg, 1);

		}

		SPI_ReceiveData(SPI1, &dummy_read, 1);

		delay();

		SPI_SendData(SPI1, &dummy_send, 1);

		SPI_ReceiveData(SPI1, &analog_read, 1);

		
		while (SPI_GetFlagStatus(SPI1, SPI_BSY_FLAG));

		SPI_PeripheralControl(SPI1, DISABLE);


	}



	return 1;

}
