/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32F401Re.h";
#include "stm32F401Re_gpio_driver.h"
#include "stm32F401Re_spi_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define MAX_LENGTH			  100

char vo Msg[MAX_LENGTH];

char vo read_byte;

uint8_t vo data_available;

uint8_t vo stop_transmission = 0;

SPI_Handle_t spi1;




/*

PA5 SPI1SCLK

PA6 SPI1MISO

PA7 SPI1MOSI

PA4 SPI1NSS


*/

static void delay() {

	for (uint32_t i = 0; i < 500000 / 2; i++);

}

void EXTI0_IRQHandler(void) {

	GPIO_IRQHandling(GPIO_PIN_NO_0);

	data_available = 1;

}

void SPI1_IRQHandler(void) {
	
	SPI_IRQHandling(&spi1);


}

static void GPIO_Interrupt_Init(void) {

	GPIO_Pin_Handle_t Button;

	Button.pGPIOx = GPIOC;

	Button.GPIO_pin_config.GPIO_PinMode = GPIO_MODE_IT_FT;

	Button.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_0;

	Button.GPIO_pin_config.GPIO_PinoutputType = GPIO_OP_TYPE_PP;

	Button.GPIO_pin_config.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&Button);

	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);

}

static void SPI1_GPIOInit() {

	GPIO_Pin_Handle_t SpiPins;

	SpiPins.pGPIOx = GPIOA;

	SpiPins.GPIO_pin_config.GPIO_AltFuncMode = 5;

	SpiPins.GPIO_pin_config.GPIO_PinMode = GPIO_MODE_ALTFN;

	SpiPins.GPIO_pin_config.GPIO_PinoutputType = GPIO_OP_TYPE_PP;

	SpiPins.GPIO_pin_config.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	SpiPins.GPIO_pin_config.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

	GPIO_PeriClockControl(GPIOA, ENABLE);

	//SCLK

	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_5;
	GPIO_Init(&SpiPins);

	//MISO
	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_6;
	GPIO_Init(&SpiPins);

	//MOSI
	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_7;
	GPIO_Init(&SpiPins);

	//
	SpiPins.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_4;
	GPIO_Init(&SpiPins);


	//NSS must be pulled to VDD even when it's not used,  nss should be connected to ground in hardware control mode or SSI should be set to 1 in software control mode
	//As if SSI is set 0 or NSS is pulled to low for master, it should be in multimaster mode in which another master is taking control
	//IF IN SOFTWARE SLAVE MANAGEMENT MODE, IF SSI IS NOT SET TO 1, MODF FLAG WILL BE SET
}

static void SPI1_Init() {

	

	spi1.pSPIx = SPI1;

	spi1.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;


	spi1.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;


	spi1.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;


	spi1.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;


	spi1.SPIConfig.SPI_DFF = SPI_DFF_8BITS;


	spi1.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;


	spi1.SPIConfig.SPI_SSM = SPI_SSM_DI;


	SPI_Init(&spi1);

	GPIO_IRQInterruptConfig(IRQ_NO_SPI1, ENABLE);



}

SPI_ApplicationEventCallback(SPI_Handle_t* pSPIHandle, uint8_t AppEv) {

	static uint8_t i;

	if (AppEv == SPI_EVENT_RX_CMPLT) {

		Msg[i++] = read_byte;

			if (read_byte == '\0' || i == MAX_LENGTH) {
			
				stop_transmission = 1;

				data_available = 0;

				Msg[i - 1] = '\0';

				i = 0;
			
			}
	
	}

}

int main(void)
{

	uint8_t dummy = 0xff;

	SPI1_GPIOInit();

	SPI1_Init();

	GPIO_Interrupt_Init();

	//SPI_SSIConfig(SPI1, ENABLE);
	SPI_SSOEConfig(SPI1, ENABLE);


	while (1) {

		stop_transmission = 0;

		while (!data_available);

		GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, DISABLE);

		SPI_PeripheralControl(SPI1, ENABLE);

		while (!stop_transmission) {

			while (SPI_SendData_IT(&spi1, &dummy, 1) == SPI_BUSY_IN_TX);

			while (SPI_ReceiveData_IT(&spi1, &read_byte, 1) == SPI_BUSY_IN_RX);

		}

		while (SPI_GetFlagStatus(SPI1, SPI_BSY_FLAG));

		SPI_PeripheralControl(SPI1, DISABLE);

		printf("Rcvd data = %s\n", Msg);

		GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);

	}
	return 1;

}
