/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <string.h>
#include <stdint.h>
#include "stm32F401Re.h";
#include "stm32F401Re_gpio_driver.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




void delay() {

    for (uint32_t i = 0; i < 500000/2; i++);

}

void EXTI0_IRQHandler(void) {

    GPIO_IRQHandling(GPIO_PIN_NO_0);

    delay();

    GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_1);

}

int main(void)
{
    GPIO_Pin_Handle_t LED;

    GPIO_Pin_Handle_t Button;

    memset(&LED, 0, sizeof(LED));

    memset(&Button, 0, sizeof(Button));

    LED.pGPIOx = GPIOC;

    LED.GPIO_pin_config.GPIO_PinMode = GPIO_MODE_OUT;

    LED.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_1;

    LED.GPIO_pin_config.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

    LED.GPIO_pin_config.GPIO_PinoutputType = GPIO_OP_TYPE_PP;

    LED.GPIO_pin_config.GPIO_PinPuPdControl = GPIO_NO_PUPD;

    Button.pGPIOx = GPIOC;

    Button.GPIO_pin_config.GPIO_PinMode = GPIO_MODE_IT_FT;

    Button.GPIO_pin_config.GPIO_PinNumber = GPIO_PIN_NO_0;

    Button.GPIO_pin_config.GPIO_PinPuPdControl = GPIO_PIN_PU;

    GPIO_PeriClockControl(GPIOC, ENABLE);

    GPIO_Init(&LED);

    GPIO_Init(&Button);

    GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);

    GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, 15);


    while (1) {

    }


}


